# Generated by Django 4.0.4 on 2022-12-06 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carousel_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='description'),
        ),
    ]
